name: Build and Push Docker Image using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Build Docker image
      run: docker-compose build
    - name: To View Docker image
      run: docker ps -a
    - name: Tag Docker image
      run: docker tag server:latest ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-ml-docker:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-ml-docker:latest
